# Generated by Django 3.0.7 on 2020-06-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200610_0203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn_no', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='books',
            name='isbn_no',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
