# Generated by Django 3.0.7 on 2020-06-10 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200610_2211'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Return',
        ),
        migrations.RemoveField(
            model_name='books',
            name='isbn_no',
        ),
    ]
